spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:mydb}
    username: ${POSTGRES_USER:tannguyen}
    password: ${POSTGRES_PASSWORD:1234}
    hikari:
      initialization-fail-timeout: -1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

  liquibase:
    # Liquibase master file location
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080