spring:
  application:
    name: backend
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

  liquibase:
    # Liquibase master file location
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health